"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ct.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'packages': ['m2secret','cffi','cryptography','M2Crypto','macholib','modulegraph','pycparser','six','altgraph','tk']
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
